# Generated by Django 5.2.1 on 2025-06-19 17:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('gpa', models.FloatField()),
                ('avg_exam_score', models.FloatField()),
                ('absent_rate', models.FloatField()),
                ('daily_study', models.IntegerField()),
                ('cram_school', models.CharField(max_length=5)),
                ('private_lesson', models.CharField(max_length=5)),
                ('private_room', models.CharField(max_length=5)),
                ('parent_edu', models.CharField(max_length=2)),
                ('study_resources', models.CharField(max_length=5)),
                ('anxiety_score', models.IntegerField()),
                ('motivation_score', models.IntegerField()),
                ('avg_sleep_time', models.IntegerField()),
                ('daily_social_media', models.IntegerField()),
                ('predicted_score', models.FloatField()),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='predictor.student')),
            ],
        ),
    ]
